# action.yml
name: "Go Coverage Commenter"
description: "Put the coverage comment in your golang project's PR"
author: "MokkeMeguru <meguru.mokke@gmail.com>"
branding:
  icon: "aperture"
  color: "blue"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
