name: "Go Coverage Commenter"
description: "Put the coverage comment in your golang project's PR"
inputs:
  exclude-regexes:
    description: "exclude-regexes separated by space"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.exclude-regexes }}
branding:
  icon: "book"
  color: "blue"
