name: pull_request
on:
  pull_request:
    types: [open, synchronize, reopened]

jobs:
  coverage_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"
      - uses: ./
        name: Wake on
        id: wake_on
        with:
          repository: ${{ github.repository }}
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
          exclude-regrexes: ""
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: coverage.md
          recreate: true
