name: Wake On
on: [push]
jobs:
  wake_on_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          go version
      - name: Wake On
        uses: ./
        id: wake_on
        with:
          repository: ${{ github.repository }}
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
          exclude-regrexes: ""
