name: Wake On
on: [push]
jobs:
  wake_on_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - run: go version
      - name: ls
        run: ls -la
        id: ls
      - name: Wake On
        uses: ./
        id: wake_on
        with:
